version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/ranger

permissions:
  - object: /home/ubuntu/ranger
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu
