server:
  port: 8080

spring:
  profiles:
    include:
      - jwt
      - jasypt
      - db

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  redis:
    port: 6379
    host: 127.0.0.1
