name: ReviewRanger Default CI

on:
  pull_request:
    branches:
      - main

env:
  REVIEWERS: sujjangOvO, beombu, JuwoongKim
  GRADLE_VERSION: 8.3
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Assign Reviewer
        uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          reviewers: ${{ env.REVIEWERS }}

  check:
    needs: assign-reviewer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Check Tests
        run: ./gradlew test

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Clean Build w/o CHECK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build -x check
