name: ReviewRanger Default CD

on:
  push:
    branches: [ "main", "REV-000" ]

env:
  RESOURCE_PATH: ./src/main/resources/application.yml
  GRADLE_VERSION: 8.3
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'temurin'
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true
  BUCKET_NAME: team12-bucket
  PROJECT_NAME: ranger
  CODE_DEPLOY_APP_NAME: team12-deploy
  DEPLOYMENT_GROUP_NAME: team12

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      # gradle caching
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # yml 파일 생성
      - name: make application.yml
        if: |
          contains(github.ref, 'main')
        run: |
          mkdir ./src/main/resources # resources 폴더 생성
          cd ./src/main/resources # resources 폴더로 이동
          touch ./application.yml # application.yml 생성
          echo "${{ secrets.YML }}" > ./application.yml
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with gradle
        run: ./gradlew clean build -x test

      - name: Docker build
        if: contains(github.ref, 'main')
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile-dev -t ${{ secrets.DOCKER_USERNAME }}/review-ranger .
          docker push ${{ secrets.DOCKER_USERNAME }}/review-ranger

      ## deploy to production
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'main')
        with:
          host: ${{ secrets.WAS_HOST }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/review-ranger
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/review-ranger
            sudo docker image prune -f
